"""KERIA-shaped long-running operation storage and HTTP resources.

This module intentionally borrows the KERIA mental model: domain endpoints
submit work, callers poll operation resources, and the operation store is the
single source of truth for pending/completed/failed state.

The deliberate adaptation for isomer verifier jobs is that operation state
is persisted directly in the operation record metadata instead of being derived
from another subsystem.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal
from uuid import uuid4

import falcon

from keri.db import dbing, koming

from .common import utc_timestamp


@dataclass(frozen=True)
class OperationStatus:
    """Structured terminal error for a failed long-running operation."""

    # HTTP-style error code exposed on failed operation resources.
    code: int
    # Human-readable terminal failure message.
    message: str
    # Optional domain-specific failure details, kept compact for operation API responses.
    details: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert the status object to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class BaseOperation:
    """Shared fields exposed by all operation resource documents."""

    # Resource name exposed over HTTP, built as "{operation_type}.{operation_id}".
    name: str
    # Operation metadata map; includes state/submittedAt/updatedAt in this PoC.
    metadata: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert the operation document to a JSON-serializable dictionary."""
        body = asdict(self)
        if isinstance(body.get("error"), OperationStatus):
            body["error"] = body["error"].to_dict()
        return body


@dataclass(frozen=True)
class PendingOperation(BaseOperation):
    """Operation that has not yet reached a terminal state."""

    # KERIA-style completion flag; pending/running operations are always false.
    done: Literal[False] = False


@dataclass(frozen=True)
class CompletedOperation(BaseOperation):
    """Operation that finished successfully and carries a response payload."""

    # Domain response payload written by the verifier worker when the job succeeds.
    response: dict[str, Any] = field(default_factory=dict)
    # KERIA-style completion flag; completed operations are terminal.
    done: Literal[True] = True


@dataclass(frozen=True)
class FailedOperation(BaseOperation):
    """Operation that reached a terminal error state."""

    # Terminal operation error written by the verifier worker.
    error: OperationStatus = field(default_factory=lambda: OperationStatus(code=500, message="unknown error"))
    # KERIA-style completion flag; failed operations are terminal.
    done: Literal[True] = True


@dataclass
class OperationRecord:
    """Persisted record for one submitted operation."""

    # Random operation id suffix generated by OperationMonitor.submit.
    oid: str
    # Operation type prefix, e.g. verify-vc, verify-vp, or verify-pair.
    type: str
    # Local submission timestamp recorded when the operation enters the store.
    start: str
    # Persisted operation state/request/response/error material.
    metadata: dict[str, Any]


class Operator(dbing.LMDBer):
    """LMDB-backed storage for isomer long-running operations."""

    TailDirPath = "keri/isomer/opr"
    AltTailDirPath = ".keri/isomer/opr"
    TempPrefix = "isomer_opr_"

    def __init__(self, name: str = "verifier", headDirPath: str | None = None, reopen: bool = True, **kwa):
        self.ops = None
        super().__init__(name=name, headDirPath=headDirPath, reopen=reopen, **kwa)

    def reopen(self, **kwa):
        """Reopen the LMDB environment and create the operation sub-database."""
        super().reopen(**kwa)
        self.ops = koming.Komer(db=self, subkey="ops.", schema=OperationRecord)
        return self.env


class OperationMonitor:
    """Track and mutate isomer long-running operation records."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"

    def __init__(
        self,
        *,
        opr: Operator | None = None,
        name: str = "verifier",
        head_dir_path: str | None = None,
        temp: bool = False,
    ):
        self.opr = opr if opr is not None else Operator(name=name, headDirPath=head_dir_path, temp=temp, reopen=True)

    def close(self) -> None:
        """Close the underlying LMDB environment."""
        self.opr.close(clear=False)

    @staticmethod
    def op_name(record: OperationRecord) -> str:
        """Return the canonical operation resource name for one record."""
        return f"{record.type}.{record.oid}"

    def submit(self, *, typ: str, request: dict[str, Any], metadata: dict[str, Any] | None = None) -> PendingOperation:
        """Create and persist one new pending operation."""
        start = utc_timestamp()
        merged_metadata = {
            "state": self.PENDING,
            "request": request,
            "submittedAt": start,
            "updatedAt": start,
            **(metadata or {}),
        }
        record = OperationRecord(
            oid=uuid4().hex,
            type=typ,
            start=start,
            metadata=merged_metadata,
        )
        self.opr.ops.pin(keys=(self.op_name(record),), val=record)
        return self.get(self.op_name(record))

    def get_record(self, name: str) -> OperationRecord | None:
        """Load the raw operation record for one resource name."""
        return self.opr.ops.get(keys=(name,))

    def require_record(self, name: str) -> OperationRecord:
        """Load one raw operation record or raise a lookup error."""
        record = self.get_record(name)
        if record is None:
            raise KeyError(f"unknown operation: {name}")
        return record

    def list_records(
        self,
        *,
        type: str | None = None,
        states: set[str] | None = None,
    ) -> list[OperationRecord]:
        """Return raw records, optionally filtered by operation type and state."""
        records: list[OperationRecord] = []
        for (_, record) in self.opr.ops.getItemIter():
            if type is not None and record.type != type:
                continue
            if states is not None and record.metadata.get("state") not in states:
                continue
            records.append(record)
        return records

    def get(self, name: str) -> BaseOperation | None:
        """Return the current operation document for one resource name."""
        record = self.get_record(name)
        if record is None:
            return None
        return self.status(record)

    def get_ops(self, *, type: str | None = None) -> list[BaseOperation]:
        """Return operation documents, optionally filtered by type."""
        return [self.status(record) for record in self.list_records(type=type)]

    def rem(self, name: str) -> bool:
        """Delete one tracked operation by resource name."""
        return self.opr.ops.rem(keys=(name,))

    def mark_running(self, name: str) -> None:
        """Mark one submitted operation as actively executing."""
        self._update(name, state=self.RUNNING)

    def complete(self, name: str, response: dict[str, Any]) -> None:
        """Persist a successful terminal response for one operation."""
        self._update(name, state=self.COMPLETED, response=response, error=None)

    def fail(self, name: str, *, code: int, message: str, details: dict[str, Any] | None = None) -> None:
        """Persist a terminal error for one operation."""
        self._update(
            name,
            state=self.FAILED,
            response=None,
            error=OperationStatus(code=code, message=message, details=details).to_dict(),
        )

    def status(self, record: OperationRecord) -> BaseOperation:
        """Translate a stored record into its current wire-format document."""
        state = record.metadata.get("state", self.PENDING)
        name = self.op_name(record)
        metadata = _wire_metadata(record.metadata)

        if state in {self.PENDING, self.RUNNING}:
            return PendingOperation(name=name, metadata=metadata)
        if state == self.COMPLETED:
            return CompletedOperation(
                name=name,
                metadata=metadata,
                response=record.metadata.get("response", {}),
            )
        if state == self.FAILED:
            error = record.metadata.get("error") or {"code": 500, "message": "operation failed"}
            return FailedOperation(name=name, metadata=metadata, error=OperationStatus(**error))
        raise ValueError(f"unknown operation state {state!r} for {name}")

    def _update(self, name: str, **updates: Any) -> None:
        """Merge metadata updates into one persisted record."""
        record = self.require_record(name)
        merged = dict(record.metadata)
        merged.update(updates)
        merged["updatedAt"] = utc_timestamp()
        self.opr.ops.pin(
            keys=(name,),
            val=OperationRecord(oid=record.oid, type=record.type, start=record.start, metadata=merged),
        )

def _wire_metadata(metadata: dict[str, Any]) -> dict[str, Any]:
    """Return the public operation metadata without internal request payloads."""
    body = dict(metadata)
    body.pop("request", None)
    return body


class OperationCollectionResource:
    """List long-running operations in the KERIA style."""

    def __init__(self, *, monitor: OperationMonitor):
        self.monitor = monitor

    def on_get(self, req: falcon.Request, resp: falcon.Response) -> None:
        """Return the current operation collection, optionally filtered by type."""
        op_type = req.params.get("type")
        resp.media = [op.to_dict() for op in self.monitor.get_ops(type=op_type)]


class OperationResource:
    """Fetch or delete a single long-running operation resource."""

    def __init__(self, *, monitor: OperationMonitor):
        self.monitor = monitor

    def on_get(self, _req: falcon.Request, resp: falcon.Response, name: str) -> None:
        """Return one current operation document."""
        operation = self.monitor.get(name)
        if operation is None:
            raise falcon.HTTPNotFound(title=f"long running operation '{name}' not found")
        resp.media = operation.to_dict()

    def on_delete(self, _req: falcon.Request, resp: falcon.Response, name: str) -> None:
        """Delete one existing operation resource."""
        if self.monitor.get(name) is None:
            raise falcon.HTTPNotFound(title=f"long running operation '{name}' not found")
        if not self.monitor.rem(name):
            raise falcon.HTTPInternalServerError(description=f"unable to delete long running operation {name}")
        resp.status = falcon.HTTP_204
