services:
  isomer-python:
    build:
      context: ..
      dockerfile: docker/isomer-python/Dockerfile

  isomer-node:
    build:
      context: ..
      dockerfile: apps/isomer-node/Dockerfile

  isomer-go:
    build:
      context: ..
      dockerfile: apps/isomer-go/Dockerfile

  isomer-dashboard:
    build:
      context: ..
      dockerfile: apps/isomer-dashboard/Dockerfile
