#!/usr/bin/env bash
set -euo pipefail

# Serve did:webs static artifacts generated by bootstrap-vrd-acdc-kli.sh and
# run the did:webs resolver against them.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${1:-$ROOT/.tmp/kli-vrd-acdc/out/env.sh}"
DWS_BIN="${DWS_BIN:-$ROOT/.venv/bin/dws}"
PYTHON_BIN="${PYTHON_BIN:-$ROOT/.venv/bin/python}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

DWS_ARTIFACT_DIR="${DWS_ARTIFACT_DIR:-$ROOT/.tmp/kli-vrd-acdc/out/did-webs-static}"
DWS_ARTIFACT_HOST="${DWS_ARTIFACT_HOST:-127.0.0.1}"
DWS_ARTIFACT_PORT="${DWS_ARTIFACT_PORT:-7677}"
DWS_RESOLVER_PORT="${DWS_RESOLVER_PORT:-7678}"
DWS_DID_PATH="${DWS_DID_PATH:-dws}"

if [[ ! -d "$DWS_ARTIFACT_DIR" ]]; then
  echo "did:webs artifact directory does not exist: $DWS_ARTIFACT_DIR" >&2
  echo "Run scripts/demo/bootstrap-vrd-acdc-kli.sh first." >&2
  exit 1
fi

if [[ -z "${SIGNER_NAME:-}" || -z "${SIGNER_PASSCODE:-}" ]]; then
  echo "SIGNER_NAME and SIGNER_PASSCODE are required. Source $ENV_FILE or set them manually." >&2
  exit 1
fi

pids=()

cleanup() {
  for pid in "${pids[@]:-}"; do
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
}
trap cleanup EXIT

echo "Serving did:webs static artifacts from $DWS_ARTIFACT_DIR on $DWS_ARTIFACT_HOST:$DWS_ARTIFACT_PORT"
"$PYTHON_BIN" -m http.server "$DWS_ARTIFACT_PORT" --bind "$DWS_ARTIFACT_HOST" --directory "$DWS_ARTIFACT_DIR" &
pids+=("$!")

echo "Starting did:webs resolver on 127.0.0.1:$DWS_RESOLVER_PORT"
"$DWS_BIN" did webs resolver-service \
  --name "$SIGNER_NAME" \
  --passcode "$SIGNER_PASSCODE" \
  --http "$DWS_RESOLVER_PORT" \
  --did-path "$DWS_DID_PATH" &
pids+=("$!")

wait
